#!/usr/bin/env python3
"""Build and deliver the Daily Market Regime Brief subscription product."""
import json, os, urllib.request, time
from datetime import date

REG_DIR = os.path.expandvars(r"${HOME}\composer-mcp-server\strategy_registry")
OUT_DIR = os.path.expandvars(r"${HOME}\trading_bot\monetization\signals")
os.makedirs(OUT_DIR, exist_ok=True)

FMP_KEY = "SoQg2skt21kYctNyoATjfzot5JJLuG65"
TODAY = date.today().isoformat()

def fmptop(path):
    url = f"https://financialmodelingprep.com/stable/{path}?apikey={FMP_KEY}"
    try:
        with urllib.request.urlopen(url, timeout=15) as r:
            return json.loads(r.read().decode())
    except:
        return None

def main():
    # 1. FMP market snapshot
    gainers = fmptop("stock-screener?marketCapMoreThan=100000000000&limit=5") or []
    losers = fmptop("stock-screener?marketCapMoreThan=100000000000&limit=5") or []
    
    # 2. Portfolio allocation signal
    fs = json.load(open(os.path.join(REG_DIR, "full_stats.json")))
    equity_val = sum(s["value"] for s in fs.values() if s.get("asset_class") == "EQUITIES")
    total_val = sum(s["value"] for s in fs.values())
    equity_pct = (equity_val / total_val * 100) if total_val > 0 else 0
    regime = "RISK-ON" if equity_pct > 70 else "BALANCED" if equity_pct > 40 else "DEFENSIVE"
    
    # 3. Sector rotation heatmap  
    sectors = {}
    for s in fs.values():
        tickers = s.get("tickers", [])
        for t in tickers:
            sectors[t] = sectors.get(t, 0) + s.get("value", 0)
    top_sectors = sorted(sectors.items(), key=lambda x: -x[1])[:5]
    
    brief = {
        "service": "Daily Market Regime Brief",
        "date": TODAY,
        "regime": regime,
        "equity_allocation_pct": round(equity_pct, 1),
        "recommendation": "",
        "top_sectors": [{"ticker": t, "total_value": round(v, 2)} for t, v in top_sectors],
        "market_snapshot": {
            "gainers": [{"symbol": g.get("symbol"), "name": g.get("companyName"), "price": g.get("price")} for g in gainers[:3]],
            "losers": [{"symbol": l.get("symbol"), "name": l.get("companyName"), "price": l.get("price")} for l in losers[:3]],
        },
        "disclaimer": "Not financial advice. Paper trading only."
    }
    
    if regime == "RISK-ON":
        brief["recommendation"] = "Favor leveraged equity strategies (TQQQ, SOXL variants). Tight trailing stops recommended."
    elif regime == "BALANCED":
        brief["recommendation"] = "Equal-weight equity and managed-futures. Reduce pure leverage exposure."
    else:
        brief["recommendation"] = "Rotate to gold, bonds, and managed futures. Reduce equity exposure below 40%."
    
    path = os.path.join(OUT_DIR, f"regime_brief_{TODAY}.json")
    json.dump(brief, open(path, "w"), indent=2)
    
    # Markdown version
    md = f"""# Daily Market Regime Brief — {TODAY}

## Regime: {regime}
**Equity allocation:** {equity_pct:.0f}% of live portfolio
**Recommendation:** {brief['recommendation']}

## Sector Heatmap
"""
    for t, v in top_sectors[:5]:
        md += f"- **{t}**: ${v:,.0f} allocated\n"
    
    md += f"\n## Market Snapshot\n"
    for g in gainers[:3]:
        md += f"- {g.get('symbol')}: {g.get('companyName')} at ${g.get('price')}\n"
    
    md += "\n---\n*Generated by BisonQuant. Not financial advice. Paper trading only.*\n"
    
    md_path = os.path.join(OUT_DIR, f"regime_brief_{TODAY}.md") 
    with open(md_path, "w") as f:
        f.write(md)
    
    print(f"Regime brief saved: {path}")
    print(f"Markdown: {md_path}")

if __name__ == "__main__":
    main()
